image: atlassian/default-image:2
pipelines:
  branches:
    master:
      - step:
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_REGION

            - export APPLICATION_NAME="APP NAME"
            - export APPLICATION_ENVIRONMENT="app-name"

            - export BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER

            - export S3_BUCKET="bucket_s3_name"

            - apt update
            - apt install -y python-pip libyaml-dev tree zip
            - pip install awscli
            - pip install boto3==1.3.0

            - mvn clean install #build using maven clean install

            - mkdir ./requirements_zip
            
            - cp ./target/app-0.0.1-SNAPSHOT.jar ./requirements_zip/output_app.jar
            
            - cp -r ./.ebextensions ./requirements_zip
            - cp ./Procfile ./requirements_zip/

            - cd ./requirements_zip/ && zip -r /tmp/artifact.zip .ebextensions * && cd ..

            - python beanstalk_deploy.py #https://bitbucket.org/awslabs/aws-elastic-beanstalk-bitbucket-pipelines-python/src/master/beanstalk_deploy.py
            