
name: Cloud Functions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy-tarcisiozao: 
    name: Deploying Tarcisio Bot
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - run: make deploy-tarcisio-bot

  deploy-formation-store-function: 
    name: Deploying FormationFunction
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - run: make deploy-formation-store-function

  deploy-render-formation-function: 
    name: Deploying RenderFormationFunction
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - run: make deploy-render-formation-function
