name: checklist-as-code/validator

on:
  repository_dispatch:
    types: [org-workflow-bot] # <--- requirement to trigger central workflows

jobs:
  validate:
    runs-on: custom-runner
    timeout-minutes: 20
    # this is a known issue limitation, in cases after the merge is done, the deleted branch event sends a commit hash with zero values.
    # check: https://github.com/SvanBoxel/organization-workflows/issues/32
    # for more context check here: https://github.com/quintoandar/global-actions-workflows/pull/46
    if: |
      github.event.client_payload.event.ref != 'refs/heads/forno' &&
      github.event.client_payload.sha != '' &&
      github.event.client_payload.event.commits[0] != ''

    outputs:
      needs_publish: ${{ fromJSON(steps.validate-checklist.outputs.needs_publish == 'true') }}
      is_valid: ${{ fromJSON(!contains(steps.validate-checklist.outputs.response, 'Error')) }}
      response: ${{steps.validate-checklist.outputs.response}}

    steps:
      - name: Logging incoming payload
        env:
          REF_PAYLOAD: ${{ toJSON(github.event.client_payload.event.ref) }}
          SHA_PAYLOAD: ${{ toJSON(github.event.client_payload.sha) }}
          BEFORE_PAYLOAD: ${{ toJSON(github.event.client_payload.event.before) }}
          AFTER_PAYLOAD: ${{ toJSON(github.event.client_payload.event.after) }}
          COMMITS_PAYLOAD: ${{ toJSON(github.event.client_payload.event.commits[0]) }}
          CLIENT_EVENT_PAYLOAD: ${{ toJSON(github.event.client_payload.event) }}
        run: |
          echo "ref:" "$REF_PAYLOAD" && 
          echo "sha:" "$SHA_PAYLOAD" && 
          echo "before:" "$BEFORE_PAYLOAD" && 
          echo "after:" "$AFTER_PAYLOAD" && 
          echo "$COMMITS_PAYLOAD" && 
          echo "$CLIENT_EVENT_PAYLOAD"

      - name: Register check-run
        uses: SvanBoxel/organization-workflows@1.3.0
        with:
          id: ${{ github.event.client_payload.id }}
          callback_url: ${{ github.event.client_payload.callback_url }}
          sha: ${{ github.event.client_payload.sha }}
          run_id: ${{ github.run_id }}
          name: ${{ github.workflow }}
          documentation: ".github/workflows/enforce-checklist-file.md"
          ## Be careful!!! If you enable parameters bellow, it's not possible revert to false
          ## Exists an bug reported here  https://github.com/SvanBoxel/organization-workflows/issues/24
          enforce: false # <--- Enforce required status check. Default: false
          enforce_admin: false # <--- Enforce required status check for admins. Default: false

      - name: Checkout to pushed repository
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}

      - name: Validating checklist file
        id: validate-checklist
        run: |
          checklist_yaml=".checklist.yaml"
          checklist_yml=".checklist.yml"
          kubedir="kube"

          if { ([ -f "${checklist_yaml}" ]) || ([ -f "${checklist_yml}" ]); } then
            git clone https://.:${{ secrets.HOMES_GITHUB_TOKEN }}@github.com/organization/checklist-tools target

            response=$(bash -x ./target/scripts/render_checklist_file --validate-file .checklist.*)

            # format response 
            # this is a known limitation of github actions
            # https://github.community/t/set-output-truncates-multiline-strings/16852/5
            response="${response//'%'/'%25'}"
            response="${response//$'\n'/'%0A'}"
            response="${response//$'\r'/'%0D'}"

            echo "::set-output name=response::$response"
            echo "::set-output name=needs_publish::true"
            echo "VALIDATE RESPONSE: $response"
          else
            if [[ -d $(pwd)/.kube || -d $(pwd)/kube ]]; then
              response="Error: The checklist.yaml|yml file was not found."
              echo "::set-output name=needs_publish::false"
              echo "::set-output name=response::$response"
            else
              echo "The kube directory and checklist file was not found."
              echo "::set-output name=needs_publish::false"
            fi
          fi

  publish-message:
    runs-on: checklist-as-code-runner
    timeout-minutes: 20
    needs: validate
    # Only publish message to persistence queue when commit is merged to default branch
    if: |
      fromJSON(needs.validate.outputs.is_valid) == true && 
      fromJSON(needs.validate.outputs.needs_publish) == true &&
      github.event.client_payload.event.ref != 'refs/heads/forno' &&
      (github.event.client_payload.event.ref == 'refs/heads/main' ||
      github.event.client_payload.event.ref == 'refs/heads/master')

    env:
      CLIENT_PAYLOAD_EVENT: ${{ toJSON(github.event.client_payload.event) }}
    steps:
      - name: Save event payload to a file
        run: echo $CLIENT_PAYLOAD_EVENT > message.txt

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1

      - name: Publish checklist content to SNS topic
        run: |
          aws sns publish --topic-arn "arn:aws:sns:us-east-1:XXXXXXX:validated-topic" --message file://message.txt

  error-handler:
    runs-on: checklist-as-code-runner
    timeout-minutes: 5
    needs: validate
    if: |
      fromJSON(needs.validate.outputs.is_valid) == false && 
      github.event.client_payload.event.ref != 'refs/heads/main' &&
      github.event.client_payload.event.ref != 'refs/heads/master' &&
      github.event.client_payload.event.ref != 'refs/heads/forno'
    env:
      VALIDATE_ERRORS: ${{ needs.validate.outputs.response }}
    steps:
      - name: Checking errors and format feedback error
        id: feedback-errors
        run: |
          FEEDBACK_VALIDATE_ERRORS=$(echo "$VALIDATE_ERRORS" | grep -A6 'Error:\|yaml\:\|field\:\|url' | grep -v "For example:")

          # Filter errors without stdout logs

          FEEDBACK_VALIDATE_ERRORS="${FEEDBACK_VALIDATE_ERRORS//'%'/'%25'}"
          FEEDBACK_VALIDATE_ERRORS="${FEEDBACK_VALIDATE_ERRORS//$'\n'/'%0A'}"
          FEEDBACK_VALIDATE_ERRORS="${FEEDBACK_VALIDATE_ERRORS//$'\r'/'%0D'}"

          echo "::set-output name=response::$FEEDBACK_VALIDATE_ERRORS"

      - name: Show log feedback error
        run: echo "Feedback error:${{ steps.feedback-errors.outputs.response }} "

      - name: Getting Pull Request number
        id: get-pr
        uses: juliangruber/find-pull-request-action@master
        with:
          state: open
          author: ${{ github.event.client_payload.event.head_commit.author.username }}
          repo: ${{ github.event.client_payload.repository.full_name }}
          branch: ${{ github.event.client_payload.event.ref }}
          github-token: ${{ github.event.client_payload.token }}

      - name: Logging pull request info
        env:
          PR_NUMBER: ${{ steps.get-pr.outputs.number }}
          REPOSITORY: ${{ github.event.client_payload.repository.name }}
        run: |
          echo "https://github.com/quintoandar/${REPOSITORY}/pull/${PR_NUMBER}" 
          echo "${{ steps.get-pr.outputs.number }}"
          echo "${{ steps.get-pr.outputs.title }}"
          echo "${{ steps.get-pr.outputs.url }}"

      - name: Sending feedback error as comment
        uses: peter-evans/create-or-update-comment@v2
        if: steps.get-pr.outputs.number != ''
        with:
          token: ${{ github.event.client_payload.token }}
          repository: ${{ github.event.client_payload.repository.full_name }}
          issue-number: ${{ steps.get-pr.outputs.number }}
          body: |
            Hi @${{ github.event.client_payload.event.pusher.name }}! 🐿️ 📖
            This message is feedback global checklist linter!

            <details><summary>⚠️ Your PR, have .checklist.yaml errors:  Click here to view check errors!</summary>
            </br>

            ${{ steps.feedback-errors.outputs.response }}

            </details>

      - name: Error handling
        run: exit 1
